const VERBOSE_TYPE_NONE = 0;
const VERBOSE_TYPE_SUMMARY = 1;
const VERBOSE_TYPE_DETAILED = 2;

export default {
	verbose: VERBOSE_TYPE_NONE,
	file: null,
	VERBOSE_TYPE_NONE,
	VERBOSE_TYPE_SUMMARY,
	VERBOSE_TYPE_DETAILED,
};
